spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_starter_dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: true

logging:
  level:
    com.starter.app: DEBUG
    org.hibernate.SQL: DEBUG
